[package]
name = "goodmetrics-derive"
version = "6.0.2"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
exponential-histogram       = { workspace = true }
proc-macro2                 = "1.0"
quote                       = "1.0"
syn                         = "2.0"
